"use client";

import React, { createContext, useContext, useEffect, useState, ReactNode } from "react";

/**
 * Lightweight UI language layer for the LiteLLM Admin UI.
 *
 * Design notes:
 * - `t()` is a plain module-level function (not a hook) so it can be used from
 *   module-level helpers such as nav config renderers. It reads a module-level
 *   `currentLang` that the provider keeps in sync, so translations apply on the
 *   next render after a language switch.
 * - The dictionary is keyed by the English source string; anything missing
 *   falls back to English, so partial translations never break the UI.
 * - The initial client render stays "en" to match the statically exported HTML
 *   (avoids hydration mismatches); the stored preference is applied in an
 *   effect right after mount.
 */

export type UiLang = "en" | "zh";

const STORAGE_KEY = "litellm_ui_lang";

/** English source string -> Simplified Chinese. */
const zhDict: Record<string, string> = {
  Cost: "费用",
  "Model Activity": "模型活动",
  "Key Activity": "API Key 活动",
  "MCP Server Activity": "MCP Server 活动",
  "Endpoint Activity": "Endpoint 活动",
  "Top Virtual Keys": "热门 Virtual Key",
  "Top Public Model Names": "热门公共模型名称",
  "Top Litellm Models": "热门 LiteLLM 模型",
  "Gateway Requests by Endpoint": "按 Endpoint 的网关请求",
  "Total Requests: {0}": "请求总数：{0}",
  "Spend: ${0}": "花费：${0}",
  "Requests: {0}": "请求：{0}",
  "Successful: {0}": "成功：{0}",
  "Failed: {0}": "失败：{0}",
  "Tokens: {0}": "Token：{0}",
  "Reusable credentials are automatically tracked as tags": "可复用凭据会自动按标签跟踪",
  "When a reusable credential is used, it will appear as a tag prefixed with": "使用可复用凭据时，它会显示为前缀为",
  "Credential:": "凭据：",
  "in this view.": "的标签，显示在本视图中。",
  "Export Usage Data": "导出用量数据",
  "Currently fetching spend data: fetched {0} / {1} pages. Charts will update periodically as data loads. Moving off of this page will stop and reset this. To continue using the UI in the meantime,": "正在获取花费数据：已加载 {0} / {1} 页。图表会随数据加载而周期性更新。离开本页面将停止并重置该过程。若要在此期间继续使用当前界面，",
  "open a new tab": "打开新标签页",
  Stop: "停止",
  "Showing partial data ({0}/{1} pages loaded)": "正在显示部分数据（已加载 {0}/{1} 页）",
  "Filter by user": "按用户筛选",
  "Select user to filter...": "选择要筛选的用户...",
  "No users found": "未找到用户",
  "Ask AI": "询问 AI",
  "Project Spend {0} - {1}": "项目花费 {0} - {1}",
  "Project Spend": "项目花费",
  "Usage Metrics": "用量指标",
  "Total Requests": "请求总数",
  "Successful Requests": "成功请求",
  "Failed Requests": "失败请求",
  "Total Tokens": "Token 总数",
  "Input Tokens": "输入 Token",
  "Output Tokens": "输出 Token",
  "Cache Read Tokens": "缓存读取 Token",
  "Cache Write Tokens": "缓存写入 Token",
  "Average Cost per Request": "单次请求平均费用",
  "Daily Spend": "每日花费",
  "Counted by the gateway when it answers a request, independent of spend logging. Deployment-wide, so it will not match the per-key or per-model breakdowns below.": "由网关在应答请求时统计，与花费记录无关；统计范围为整个部署，因此与下方按 key 或按模型的细分可能不一致。",
  "Includes requests that failed to route to a provider, tool usage failures, and other request errors where the provider cannot be determined.": "包括无法路由到 provider 的请求、工具调用失败，以及其他无法确定 provider 的请求错误。",
  "Counted by the gateway middleware as each request is answered. Covers LLM, MCP and A2A endpoints across the whole deployment.": "由网关中间件在每个请求应答时统计，涵盖整个部署中的 LLM、MCP 与 A2A endpoint。",
  "Usage View": "用量视图",
  "Select the usage data you want to view": "选择你要查看的用量数据",
  "Global Usage": "全局用量",
  "Your Usage": "我的用量",
  "Organization Usage": "组织用量",
  "Your Organization Usage": "我的组织用量",
  "Team Usage": "团队用量",
  "Customer Usage": "客户用量",
  "Tag Usage": "标签用量",
  "Agent Usage (A2A)": "Agent 用量（A2A）",
  "User Usage": "用户用量",
  "User Agent Activity": "用户 Agent 活动",
  "View usage across all resources": "查看所有资源的用量",
  "View your usage": "查看我的用量",
  "View your own usage": "查看你自己的用量",
  "View organization-level usage": "查看组织级别的用量",
  "View usage across all organizations": "查看所有组织的用量",
  "View your organization's usage": "查看你所在组织的用量",
  "View usage by team": "按团队查看用量",
  "View usage by customer accounts": "按客户账户查看用量",
  "View usage grouped by tags": "按标签分组的用量",
  "View usage by AI agents": "按 AI Agent 查看用量",
  "View usage by individual users": "按单个用户查看用量",
  "View detailed user agent activity logs": "查看详细的用户 Agent 活动日志",
  "Public Model Name": "公共模型名称",
  "Litellm Model Name": "LiteLLM 模型名称",
  "Filter: {0}": "筛选：{0}",
  "Ask about your spend, models, keys, and trends": "询问关于花费、模型、key 与趋势的问题",
  "Select a model (optional, defaults to gpt-4o-mini)": "选择模型（可选，默认为 gpt-4o-mini）",
  "Ask a question about your usage": "就你的用量提问",
  "e.g. \"Which model costs me the most?\"": "例如：“哪个模型花费最高？”",
  "Thinking...": "思考中...",
  "Ask about your usage...": "询问你的用量...",
  Send: "发送",
  "Clear chat": "清空对话",
  "Enter to send": "按 Enter 发送",
  "Failed to get response. Please try again.": "获取响应失败，请重试。",
  "Filter by {0}": "按 {0} 筛选",
  "Select {0} to filter...": "选择要筛选的 {0}...",
  "{0} Spend Overview": "{0} 花费概览",
  "Total Spend": "总花费",
  "Total Spend: ${0}": "总花费：${0}",
  "Total {0}s: {1}": "共 {0} 个：{1}",
  "Spend by {0}:": "按 {0} 的花费：",
  "{0}: ${1}": "{0}：${1}",
  "...and {0} more": "...及另外 {0} 个",
  "Spend Per {0}": "每个 {0} 的花费",
  "Showing Top 5 by Spend": "按花费显示前 5",
  "Get Started by Tracking cost per {0}": "从按 {0} 跟踪花费开始",
  here: "这里",
  Spend: "消费",
  Successful: "成功",
  Failed: "失败",
  Tokens: "Token",
  "Top Agents": "热门 Agent",
  "Top Agents Driving Spend": "花费最高的 Agent",
  "Provider Usage": "Provider 用量",
  Provider: "提供商",
  "Request / Token Consumption": "请求 / Token 消耗",
  "Agent Activity": "Agent 活动",
  "Currently fetching agent data: fetched {0} / {1} pages. Charts will update periodically as data loads. Moving off of this page will stop and reset this. To continue using the UI in the meantime,": "正在获取 Agent 数据：已加载 {0} / {1} 页。图表会随数据加载而周期性更新。离开本页面将停止并重置该过程。若要在此期间继续使用当前界面，",
  "Showing partial agent data ({0}/{1} pages loaded)": "正在显示部分 Agent 数据（已加载 {0}/{1} 页）",
  "Filter by team": "按团队筛选",
  "Spend by Provider": "按 Provider 的花费",
  "Show Zero Spend": "显示零花费",
  "Show Unknown": "显示未知",
  "Requests that failed to route to a provider": "无法路由到 provider 的请求",
  Model: "模型",
  "Spend (USD)": "消费 (USD)",
  "Table View": "表格视图",
  "Chart View": "图表视图",
  Endpoint: "Endpoint",
  "Successful / Failed": "成功 / 失败",
  "Total Request": "请求总数",
  "Success Rate": "成功率",
  "Success vs Failed Requests by Endpoint": "各 Endpoint 成功与失败请求对比",
  "Endpoint Usage Trends": "Endpoint 用量趋势",
  Team: "团队",
  Organization: "组织",
  "User ID": "用户 ID",
  "Key ID": "Key ID",
  "Loading key...": "正在加载 Key…",
  "Virtual Keys": "虚拟密钥",
  "Every key that authenticates requests to the gateway.": "每个用于向网关发起请求认证的 API Key。",
  "Loading keys...": "正在加载 API Key…",
  "No keys found": "未找到 API Key",
  "Search by key alias…": "按 Key 别名搜索…",
  Filters: "筛选",
  "Narrow down virtual keys": "按条件筛选虚拟 API Key",
  "Select a team…": "选择一个团队…",
  "No teams found": "未找到团队",
  "Select an organization…": "选择一个组织…",
  "No organizations found": "未找到组织",
  "Enter User ID…": "输入用户 ID…",
  "Enter Key ID…": "输入 Key ID…",
  Budget: "预算",
  Blocked: "已封锁",
  "Blocked by SCIM (external identity provider deactivated or deleted the owning user).": "已被 SCIM 封锁（外部身份提供方已停用或删除所属用户）。",
  "Blocked. Requests using this key will be rejected with 401.": "已封锁。使用此 Key 的请求将返回 401。",
  Expired: "已过期",
  "This key has passed its expiry date.": "此 Key 已超过过期时间。",
  Active: "正常",
  "This key is not blocked and has not expired.": "此 Key 未被封锁且未过期。",
  "User Alias": "用户别名",
  "User Email": "用户邮箱",
  Key: "Key",
  User: "用户",
  "Displays the first available value: User Alias, User Email, or User ID.": "显示首个可用的值：用户别名、用户邮箱或用户 ID。",
  "Created At": "创建时间",
  "Created By": "创建人",
  "Updated At": "更新时间",
  Never: "从未",
  "Last Active": "最近活跃",
  "This is a new field and is not backfilled. Only new key usage will update this value.": "这是新字段，不会回填历史数据。仅新的 Key 使用记录会更新此值。",
  Unknown: "未知",
  Expires: "过期时间",
  "Spend / Budget": "消费 / 预算",
  "Budget Reset": "预算重置",
  Models: "模型",
  "Rate Limits": "速率限制",
  "TPM: {0}": "TPM：{0}",
  "RPM: {0}": "RPM：{0}",
  Unlimited: "不限",
  "Team alias": "团队别名",
  "Team ID": "团队 ID",
  "Loading teams...": "正在加载团队…",
  "Search teams by name or ID…": "按团队名称或 ID 搜索…",
  "Narrow down your teams": "按条件筛选团队",
  "Enter team alias…": "输入团队别名…",
  "Enter team ID…": "输入团队 ID…",
  Resources: "资源",
  Created: "创建时间",
  Members: "成员",
  Actions: "操作",
  "Edit team": "编辑团队",
  "Copy team ID": "复制团队 ID",
  "Delete team": "删除团队",
  "Team ID copied": "团队 ID 已复制",
  "Open team actions": "打开团队操作",
  members: "成员",
  models: "模型",
  keys: "Key",
  Reset: "重置",
  "Max Budget": "预算上限",
  "Unlimited only": "仅显示不限",
  "{0} to {1}": "{0} 至 {1}",
  any: "任意",
  "No matching budgets": "无匹配的预算",
  "No budgets yet": "暂无预算",
  "No budget matches your search or filters.": "没有符合当前搜索或筛选条件的预算。",
  "Create a budget to set spend, TPM and RPM limits for customers.": "创建预算以设置客户的消费、TPM 和 RPM 限额。",
  "You do not have access to budgets": "您无权访问预算",
  "Could not load budgets": "无法加载预算",
  "Ask a proxy admin to grant you the admin viewer role.": "请联系 proxy 管理员为您授予 admin viewer 角色。",
  "Loading budgets…": "正在加载预算…",
  "Search by budget ID…": "按预算 ID 搜索…",
  "Narrow down your budgets": "按条件筛选预算",
  "Max Budget (USD)": "预算上限 (USD)",
  Min: "最小值",
  "Minimum max budget": "最小预算上限",
  Max: "最大值",
  "Maximum max budget": "最大预算上限",
  "Created from": "创建时间起",
  "Created to": "创建时间止",
  hourly: "每小时",
  daily: "每天",
  weekly: "每周",
  monthly: "每月",
  "Not set": "未设置",
  "n/a": "不适用",
  "Open budget actions": "打开预算操作",
  "Edit budget": "编辑预算",
  "Delete budget": "删除预算",
  "Budget ID": "预算 ID",
  "SSO ID": "SSO ID",
  Role: "角色",
  "Try adjusting your search or filters.": "请尝试调整搜索词或筛选条件。",
  "Loading users…": "正在加载用户…",
  "Search by email…": "按邮箱搜索…",
  "Narrow down your users": "按条件筛选用户",
  "Enter user ID…": "输入用户 ID…",
  "Enter SSO ID…": "输入 SSO ID…",
  "Select a role…": "选择角色…",
  "No roles found": "未找到角色",
  "SSO ID is the ID of the user in the SSO provider. If the user is not using SSO, this will be null.": "SSO ID 是用户在 SSO 提供方中的 ID。如果用户未使用 SSO，则为 null。",
  "Deactivated via SCIM (external identity provider). The user's virtual keys are blocked.": "已通过 SCIM（外部身份提供方）停用。该用户的虚拟 API Key 已被封锁。",
  "Open user actions": "打开用户操作",
  "Edit user": "编辑用户",
  "Reset password": "重置密码",
  "User ID copied": "用户 ID 已复制",
  "Copy user ID": "复制用户 ID",
  "Delete user": "删除用户",
  Email: "邮箱",
  Status: "状态",
  Inactive: "未激活",
  "Global Proxy Role": "全局 Proxy 角色",
  "Budget (USD)": "预算 (USD)",
  Keys: "密钥",
  "No Keys": "无 Key",
  "About SSO ID": "关于 SSO ID",
  "No reset": "不重置",
  Admin: "管理员",
  "Search a team": "搜索团队",
  "Default Teams": "默认团队",
  "New users are added to these teams. Only teams that already exist can be selected.": "新用户将被添加到这些团队。只能选择已存在的团队。",
  "Team {0}": "团队 {0}",
  Remove: "移除",
  "Max Budget in Team (USD)": "团队预算上限 (USD)",
  Optional: "选填",
  "Team Role": "团队角色",
  "Add Team": "添加团队",
  "Default Role": "默认角色",
  "Reset Budget": "预算重置周期",
  "Default Models": "默认模型",
  None: "无",
  "{0} max budget": "{0} 的预算上限",
  "Default user settings updated successfully": "默认用户设置已更新成功",
  "Failed to update default user settings": "更新默认用户设置失败",
  "Role assigned to new users": "分配给新用户的角色",
  "Default maximum budget for new users": "新用户的默认预算上限",
  "How often the default budget resets": "默认预算的重置频率",
  "Models new users can access": "新用户可访问的模型",
  Cancel: "取消",
  "Saving...": "保存中…",
  "Save Changes": "保存更改",
  "Default User Settings": "默认用户设置",
  "Applied to every new internal user created through SSO or the user management APIs.": "应用于通过 SSO 或用户管理 API 创建的每个新内部用户。",
  "Could not load the default user settings.": "无法加载默认用户设置。",
  "Edit Settings": "编辑设置",
  "All Proxy Models": "所有 Proxy 模型",
  "No Default Models": "无默认模型",
  "Request Logs": "请求日志",
  "Audit Logs": "审计日志",
  "Deleted Keys": "已删除的密钥",
  "Deleted Teams": "已删除的团队",
  "✨ Enterprise Feature.": "✨ 企业版功能。",
  "This is a LiteLLM Enterprise feature, and requires a valid key to use.": "这是 LiteLLM 企业版功能，需要有效的密钥才能使用。",
  "Here's a preview of what Audit Logs offer:": "以下是审计日志功能预览：",
  "Audit Logs Preview": "审计日志预览",
  LLM: "LLM",
  MCP: "MCP",
  Agent: "Agent",
  "Back to Logs": "返回日志",
  Time: "时间",
  Type: "类型",
  Success: "成功",
  Failure: "失败",
  "Session ID": "会话 ID",
  "Request ID": "请求 ID",
  "session total": "会话总计",
  "incl. {0} from {1} MCP": "含 MCP 的 {0}（共 {1} 条）",
  "Duration (s)": "耗时（秒）",
  "TTFT (s)": "首字延迟 TTFT（秒）",
  "Team Name": "团队名称",
  "Key Hash": "密钥哈希",
  "Key Alias": "密钥别名",
  "Internal User": "内部用户",
  "End User": "终端用户",
  Tags: "标签",
  "{0} LLM": "LLM ×{0}",
  "{0} Agent": "Agent ×{0}",
  "{0} MCP": "MCP ×{0}",
  "No matching requests": "没有匹配的请求",
  "No requests yet": "暂无请求",
  "No requests match your filters for this time range.": "此时间范围内没有符合筛选条件的请求。",
  "Requests proxied through LiteLLM will appear here.": "通过 LiteLLM 代理的请求将显示在这里。",
  "Loading request logs…": "正在加载请求日志…",
  "Search by Request ID": "按请求 ID 搜索",
  "Narrow down request logs": "缩小请求日志范围",
  "Error Code": "错误码",
  "Error Message": "错误信息",
  "Public model / search tool": "公共模型 / 搜索工具",
  "Search or select a team": "搜索或选择团队",
  "Search a key alias": "搜索密钥别名",
  "No key aliases found": "未找到密钥别名",
  "Model ID: {0}": "模型 ID：{0}",
  "Search a model": "搜索模型",
  "No models found": "未找到模型",
  "Search an end user": "搜索终端用户",
  "No end users in this time range": "此时间范围内没有终端用户",
  "Use custom code: {0}": "使用自定义错误码：{0}",
  "Select or type an error code": "选择或输入错误码",
  "No error codes found": "未找到错误码",
  "All Statuses": "全部状态",
  "Enter error message…": "输入错误信息…",
  "Enter key hash…": "输入密钥哈希…",
  "Enter session ID…": "输入会话 ID…",
  "Enter public model or search tool…": "输入公共模型或搜索工具…",
  "Custom Range": "自定义时间范围",
  to: "至",
  "Live Tail": "实时流",
  "Reset Filters": "重置筛选",
  "Auto-refreshing every 15 seconds": "每 15 秒自动刷新",
  "Last Minute": "最近 1 分钟",
  "Last 15 Minutes": "最近 15 分钟",
  "Last Hour": "最近 1 小时",
  "Last 4 Hours": "最近 4 小时",
  "Last 24 Hours": "最近 24 小时",
  "Last 7 Days": "最近 7 天",
  "No matching audit logs": "没有匹配的审计日志",
  "No audit logs yet": "暂无审计日志",
  "No audit log entries match your filters.": "没有符合筛选条件的审计日志记录。",
  "Administrative changes to keys, teams, users, and models will appear here.": "对密钥、团队、用户和模型的管理操作将显示在这里。",
  "Loading audit logs…": "正在加载审计日志…",
  "Narrow down audit log entries": "缩小审计日志范围",
  "Object ID": "对象 ID",
  "Enter object ID…": "输入对象 ID…",
  "Changed By": "操作人",
  Action: "操作",
  "All Actions": "全部操作",
  Table: "数据表",
  "All Tables": "全部数据表",
  Updated: "更新",
  Deleted: "删除",
  Rotated: "轮换",
  Teams: "团队",
  Users: "用户",
  Organizations: "组织",
  Timestamp: "时间戳",
  "API Key (Hash)": "API Key（哈希）",
  "All Models": "全部模型",
  "Your Models": "我的模型",
  "Add Model": "添加模型",
  "Auto-Routers": "Auto-Router",
  "LLM Credentials": "LLM 凭据",
  "Pass-Through Endpoints": "透传端点",
  "Health Status": "健康状态",
  "Model Retry Settings": "模型重试设置",
  "Model Group Alias": "模型组别名",
  "Price Data Reload": "价格数据重载",
  "Model Management": "模型管理",
  "Add and manage models for the proxy": "为代理添加并管理模型",
  "Add models for teams you are an admin for.": "为您作为管理员所在的团队添加模型。",
  "Last Refreshed: {0}": "上次刷新：{0}",
  "Refresh models": "刷新模型",
  Personal: "个人",
  "Model deleted successfully": "模型删除成功",
  "Model paused": "模型已暂停",
  "Model resumed": "模型已恢复",
  "To access these models, create a Virtual Key without selecting a team on the ": "要访问这些模型，请在",
  "To access these models, create a Virtual Key and select Team as \"{0}\" on the ": "要访问这些模型，请创建 Virtual Key 并将团队选为“{0}”，然后在",
  "Virtual Keys page": "Virtual Keys 页面",
  "Delete Model": "删除模型",
  "This action cannot be undone.": "此操作无法撤销。",
  "Are you sure you want to delete this model?": "确定要删除此模型吗？",
  "Model Information": "模型信息",
  "Model Name": "模型名称",
  "Not Set": "未设置",
  "LiteLLM Model Name": "LiteLLM 模型名称",
  "No models match your search or filters. Try resetting them.": "没有符合搜索或筛选条件的模型。请尝试重置筛选。",
  "Wildcard Models (*)": "通配模型（*）",
  "All Model Access Groups": "全部模型访问组",
  "Loading models…": "正在加载模型…",
  "Search model names…": "搜索模型名称…",
  "Current team": "当前团队",
  View: "视图",
  "Current Team Models": "当前团队模型",
  "All Available Models": "全部可用模型",
  "Model Settings": "模型设置",
  "Narrow down models + endpoints": "缩小模型与端点范围",
  "Filter by Public Model Name": "按公共模型名称筛选",
  "Model Access Group": "模型访问组",
  "Filter by Model Access Group": "按模型访问组筛选",
  "No model access groups found": "未找到模型访问组",
  "Unknown provider": "未知提供商",
  "Copy LiteLLM model name": "复制 LiteLLM 模型名称",
  "LiteLLM model name copied": "已复制 LiteLLM 模型名称",
  Credentials: "凭据",
  "About credential types": "关于凭据类型",
  "Credential types": "凭据类型",
  Reusable: "可复用",
  "Credentials saved in LiteLLM that can be added to models repeatedly.": "保存在 LiteLLM 中、可反复添加到模型的凭据。",
  Manual: "手动",
  "Credentials added directly during model creation or defined in the config file.": "在创建模型时直接添加，或在配置文件中定义的凭据。",
  "Defined in config": "在配置中定义",
  "Unknown date": "未知日期",
  "Cost per 1M tokens": "每 100 万 Token 费用",
  "+{0} more": "还有 {0} 项",
  "Config models cannot be paused from the dashboard. Pause is DB-backed.": "配置模型无法在仪表盘中暂停。暂停需基于数据库。",
  "Only proxy admins can pause or resume a model.": "只有代理管理员可以暂停或恢复模型。",
  "Resume model — restore normal routing.": "恢复模型——恢复正常路由。",
  "Pause model — stop routing requests until resumed.": "暂停模型——暂停请求路由，直至恢复。",
  "Config model cannot be deleted on the dashboard. Please delete it from the config file.": "配置模型无法在仪表盘中删除。请从配置文件中删除。",
  "Delete model": "删除模型",
  "Resume model": "恢复模型",
  "Pause model": "暂停模型",
  "Model ID": "模型 ID",
  Costs: "费用",
  "DB Model": "数据库模型",
  "Config Model": "配置模型",
  "Deleted auto router: {0}": "已删除 Auto Router：{0}",
  "Failed to delete auto router: {0}": "删除 Auto Router 失败：{0}",
  "Auto routers": "Auto Router",
  "Auto routers sit above your deployments and pick a model per request. They are called like any other model, so clients keep using a single model name.": "Auto Router 位于部署之上，为每个请求选择一个模型。它与其他模型一样被调用，客户端只需继续使用同一个模型名称。",
  "Add Auto Router": "添加 Auto Router",
  "Routes each request to a model by classifying its complexity. Called like any other model, so clients keep using a single model name.": "通过判定请求复杂度，将其路由到合适的模型。与普通模型一样被调用，客户端可继续使用同一个模型名称。",
  "Delete Auto Router": "删除 Auto Router",
  "Are you sure you want to delete \"{0}\"? Any client still calling this model name will start failing.": "确定要删除“{0}”吗？任何仍在调用此模型名称的客户端将开始报错。",
  "Auto router": "Auto Router",
  Name: "名称",
  ID: "ID",
  "No auto routers yet": "暂无 Auto Router",
  "Create an auto router to pick the right model per request instead of pinning one.": "创建一个 Auto Router，按请求选择合适的模型，而不是固定使用单一模型。",
  "An auto router picks the right model per request instead of pinning one.": "Auto Router 会按请求选择合适的模型，而不是固定使用单一模型。",
  "Loading auto routers…": "正在加载 Auto Router…",
  "+{0}": "+{0}",
  "Open actions for {0}": "打开 {0} 的操作",
  "Delete auto router": "删除 Auto Router",
  "Routes to": "路由到",
  "Default model": "默认模型",
  "LLM Classifier": "LLM 分类器",
  Heuristic: "启发式",
  Semantic: "语义",
  Adaptive: "自适应",
  Quality: "质量优先",
  "Help shape cost optimization": "帮助我们优化成本",
  "We're collecting suggestions for cost optimization improvements across routing, budgets, and more. Let us know what you'd like to see.": "我们正在收集有关路由、预算等方面的成本优化改进建议。欢迎告诉我们你希望看到什么。",
  "Share Feedback": "分享反馈",
  "Dismiss banner": "关闭横幅",
  "AI GATEWAY": "AI 网关",
  OBSERVABILITY: "可观测性",
  "ACCESS CONTROL": "访问控制",
  "DEVELOPER TOOLS": "开发者工具",
  SETTINGS: "设置",
  "AI Gateway": "AI 网关",
  Observability: "可观测性",
  "Access Control": "访问控制",
  "Developer Tools": "开发者工具",
  Playground: "演练场",
  "Models + Endpoints": "模型 + 端点",
  Agentic: "智能体",
  Agents: "智能体",
  "Workflow Runs": "工作流运行",
  Memory: "记忆",
  "MCP Servers": "MCP 服务器",
  Skills: "技能",
  Guardrails: "防护栏",
  Policies: "策略",
  Tools: "工具",
  "Search Tools": "搜索工具",
  "Vector Stores": "向量存储",
  "Tool Policies": "工具策略",
  Usage: "用量",
  "Cost Optimization": "成本优化",
  Logs: "日志",
  "Guardrails Monitor": "防护栏监控",
  Projects: "项目",
  "Internal Users": "内部用户",
  "Access Groups": "访问组",
  Budgets: "预算",
  "API Reference": "API 参考",
  "AI Hub": "AI 中心",
  "Learning Resources": "学习资源",
  "Response Cache": "响应缓存",
  Experimental: "实验功能",
  Prompts: "提示词",
  "API Playground": "API 演练场",
  "Tag Management": "标签管理",
  "Old Usage": "旧版用量",
  Settings: "设置",
  "Router Settings": "路由设置",
  "Logging & Alerts": "日志与告警",
  "Admin Settings": "管理员设置",
  "Cost Tracking": "成本追踪",
  "UI Theme": "界面主题",
  "Expand sidebar": "展开侧边栏",
  "Collapse sidebar": "收起侧边栏",
  Docs: "文档",
  "Thanks for using LiteLLM!": "感谢使用 LiteLLM！",
  Login: "登录",
  "Access your LiteLLM Admin UI.": "访问你的 LiteLLM 管理界面。",
  "Default Credentials": "默认凭据",
  "By default, Username is": "默认情况下，用户名为",
  "and Password is your set LiteLLM Proxy": "，密码是你设置的 LiteLLM Proxy",
  "Need to set UI credentials or SSO?": "需要配置登录凭据或 SSO？",
  "Check the documentation": "查看文档",
  Username: "用户名",
  Password: "密码",
  "Please enter your username": "请输入用户名",
  "Please enter your password": "请输入密码",
  "Enter your username": "输入用户名",
  "Enter your password": "输入密码",
  "Logging in...": "登录中...",
  "Login with SSO": "使用 SSO 登录",
  "Please configure SSO to log in with SSO.": "请先配置 SSO，才能使用 SSO 登录。",
  Worker: "Worker",
  "Choose a worker to connect to": "选择要连接的 Worker",
  "Admin UI Disabled": "管理界面已禁用",
  "The Admin UI has been disabled by the administrator. To re-enable it, please update the following environment variable:": "管理界面已被管理员禁用。要重新启用，请更新以下环境变量：",
  "Single Sign-On (SSO) is enabled. LiteLLM no longer automatically redirects to the SSO login flow upon loading this page. To re-enable auto-redirect-to-SSO, set": "已启用单点登录（SSO）。LiteLLM 不再在加载此页面时自动跳转到 SSO 登录流程。要重新启用自动跳转 SSO，请设置",
  "in your environment configuration.": "环境变量。",
  Search: "搜索",
  "Clear all": "清除全部",
  Refresh: "刷新",
  Columns: "列显示",
  "Rows per page": "每页行数",
  "No results": "无结果",
  "Showing {0}-{1} of {2}": "显示 {0}-{1}，共 {2} 条",
  "Page {0} of {1}": "第 {0} 页，共 {1} 页",
  "Go to first page": "跳到第一页",
  "Go to previous page": "上一页",
  "Go to next page": "下一页",
  "Go to last page": "跳到最后一页",

  "No limit": "无限制",

  // ---- Router settings & page shells (2026-08-18) ----
  "Routing Settings": "路由设置",
  "Configure how requests are routed to deployments": "配置请求如何路由到部署",
  "Routing Strategy": "路由策略",
  "Enable Tag Filtering": "启用标签过滤",
  "Learn more": "了解更多",
  "Reliability & Retries": "可靠性与重试",
  "Configure retry logic and failure handling": "配置重试逻辑与失败处理",
  "Latency-Based Configuration": "延迟路由配置",
  "Fine-tune latency-based routing behavior": "微调基于延迟的路由行为",
  Loadbalancing: "负载均衡",
  "Routing Groups": "路由分组",
  Fallbacks: "降级回退",
  "Prompt Caching": "提示词缓存",
  General: "通用",
  Setting: "设置项",
  Value: "值",
  Update: "更新",
  "In DB": "在数据库中",
  "In Config": "在配置中",
  "Automatic Anthropic prompt caching": "自动 Anthropic 提示词缓存",
  "Cache lifetime (TTL)": "缓存生存时间（TTL）",
  "5m (default)": "5 分钟（默认）",
  Default: "默认",
  "Allowed Fails": "允许失败次数",
  "Cooldown Time": "冷却时间",
  "Number of Retries": "重试次数",
  Timeout: "超时",
  "Retry After": "重试间隔",
  "Enable Weighted Failover": "启用加权故障转移",
  "Routing strategy to use for load balancing across deployments": "负载均衡多个部署时所用的路由策略",
  "Enable tag-based routing to route requests based on tags": "启用基于标签的路由，按标签分发请求",
  "Number of times a deployment can fail before being added to cooldown": "部署进入冷却前允许失败的次数",
  "Time in seconds to cooldown a deployment after failure": "部署失败后的冷却时间（秒）",
  "Timeout for requests in seconds": "请求超时时间（秒）",
  "Minimum time to wait before retrying a failed request in seconds": "重试失败请求前的最小等待时间（秒）",
  "Number of retries for failed requests": "失败请求的重试次数",
  "Aliases for model groups": "模型组的别名",
  "Randomly picks a deployment from the list. Simple and fast.": "从列表中随机选择一个部署。简单快速。",
  "Sliding window to look back over when calculating the average latency of a deployment. Default - 1 hour (in seconds).": "计算部署平均延迟时回看的滑动窗口。默认 1 小时（单位秒）。",
  "Shuffle between deployments within this % of the lowest latency. Default - 0 (i.e. always pick lowest latency).": "在最低延迟的该百分比范围内随机选择部署。默认 0（即始终选择最低延迟）。",
  "Create New Key": "创建新密钥",
  "Invite User": "邀请用户",
  "Bulk Invite Users": "批量邀请用户",
  "Select Users": "选择用户",
  "Cancel Selection": "取消选择",
  "Export Data": "导出数据",
  "Select Time Range": "选择时间范围",
  Examples: "示例",
  "Your Teams": "我的团队",
  "Available Teams": "可用团队",
  "Default Team Settings": "默认团队设置",
  "Create Team": "创建团队",
  "Create Budget": "创建预算",
  "Manage teams, members, and their access to models and budgets": "管理团队、成员及其对模型和预算的访问",
  "Spend, TPM and RPM limits you can assign to customers.": "可分配给客户的消费、TPM 和 RPM 限额。",
};

// Initialize synchronously from storage so the FIRST client render (hydration)
// already uses the stored language. Static-export HTML is prerendered in
// English; React recovers from the text mismatch by client-rendering the
// subtree, which then shows the translated strings.
let currentLang: UiLang = "en";
if (typeof window !== "undefined") {
  try {
    if (window.localStorage.getItem(STORAGE_KEY) === "zh") currentLang = "zh";
  } catch {
    // localStorage unavailable — default to English.
  }
}

/**
 * Translate an English source string; falls back to the input itself.
 * Supports `{0}`, `{1}`, ... placeholders interpolated from `args`, e.g.
 * `t("Page {0} of {1}", page, total)`.
 */
export function t(text: string, ...args: (string | number)[]): string {
  const resolved = currentLang !== "zh" ? text : (zhDict[text] ?? text);
  if (args.length === 0) return resolved;
  return resolved.replace(/\{(\d+)\}/g, (match, index) => {
    const arg = args[Number(index)];
    return arg === undefined ? match : String(arg);
  });
}

interface LanguageContextType {
  lang: UiLang;
  setLang: (lang: UiLang) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

/**
 * Graceful variant used by chrome components that may also render on pages
 * mounted outside the provider (e.g. tests): falls back to English instead of
 * throwing.
 */
export function useLanguage(): LanguageContextType {
  const context = useContext(LanguageContext);
  if (context) return context;
  return {
    lang: "en",
    setLang: () => {
      // No provider mounted: ignore (static export always mounts one).
    },
  };
}

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<UiLang>("en");

  const applyLang = (next: UiLang) => {
    currentLang = next;
    if (typeof document !== "undefined") {
      document.documentElement.lang = next === "zh" ? "zh-CN" : "en";
    }
  };

  // Apply the stored preference after mount (keeps first render == exported HTML).
  useEffect(() => {
    try {
      const stored = window.localStorage.getItem(STORAGE_KEY);
      if (stored === "zh" || stored === "en") {
        applyLang(stored);
        setLangState(stored);
      }
    } catch {
      // localStorage unavailable (private mode etc.) — stay on English.
    }
  }, []);

  const setLang = (next: UiLang) => {
    applyLang(next);
    setLangState(next);
    try {
      window.localStorage.setItem(STORAGE_KEY, next);
    } catch {
      // Ignore storage failures; switch still applies for this session.
    }
    // Static export: prerendered HTML + RSC payload cannot be swapped in place
    // for every subtree, so a full reload guarantees the whole page re-renders
    // in the new language (module init reads storage synchronously).
    if (typeof window !== "undefined") {
      window.location.reload();
    }
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang }}>
      {/* Keyed remount: t() reads module-level state at render time, so children
          must be re-created (not just re-rendered) for every consumer to pick up
          the new language, including components that do not consume context. */}
      <React.Fragment key={lang}>{children}</React.Fragment>
    </LanguageContext.Provider>
  );
};
